import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding EarnQuest database...");

  // 1. Clean existing records in development
  await prisma.auditLog.deleteMany();
  await prisma.userAchievement.deleteMany();
  await prisma.achievement.deleteMany();
  await prisma.earningVerification.deleteMany();
  await prisma.ledgerEntry.deleteMany();
  await prisma.projectFile.deleteMany();
  await prisma.project.deleteMany();
  await prisma.userMissionProgress.deleteMany();
  await prisma.userMission.deleteMany();
  await prisma.missionTool.deleteMany();
  await prisma.missionStep.deleteMany();
  await prisma.missionVersion.deleteMany();
  await prisma.mission.deleteMany();
  await prisma.opportunityScore.deleteMany();
  await prisma.opportunitySource.deleteMany();
  await prisma.opportunity.deleteMany();
  await prisma.aIToolVerification.deleteMany();
  await prisma.aIToolSource.deleteMany();
  await prisma.aITool.deleteMany();
  await prisma.hardwareProfile.deleteMany();
  await prisma.userProfile.deleteMany();
  await prisma.user.deleteMany();

  // 2. Create Users
  const adminPasswordHash = await bcrypt.hash("AdminPass123!", 10);
  const adminUser = await prisma.user.create({
    data: {
      email: "admin@earnquest.local",
      passwordHash: adminPasswordHash,
      role: "ADMIN",
      profile: {
        create: {
          displayName: "EarnQuest Operator",
          bio: "Platform Administrator & Quality Assurance",
          xp: 2500,
          level: 5,
        },
      },
      hardwareProfile: {
        create: {
          os: "Windows",
          browser: "Chrome",
          cpuCores: 8,
          ramGb: 16,
          hasGpu: true,
          gpuRenderer: "NVIDIA GeForce RTX 3070",
          tier: "TIER_3_POWER",
        },
      },
    },
  });

  const creatorPasswordHash = await bcrypt.hash("CreatorPass123!", 10);
  const demoUser = await prisma.user.create({
    data: {
      email: "creator@earnquest.local",
      passwordHash: creatorPasswordHash,
      role: "USER",
      profile: {
        create: {
          displayName: "Alex Rivera",
          bio: "Building my first digital services business with free AI tools.",
          country: "United States",
          xp: 450,
          level: 2,
          streakDays: 3,
        },
      },
      hardwareProfile: {
        create: {
          os: "macOS",
          browser: "Chrome",
          cpuCores: 8,
          ramGb: 8,
          hasGpu: false,
          tier: "TIER_1_LITE",
        },
      },
    },
  });

  // 3. Create 10 Real Free Tools
  const toolsData = [
    {
      slug: "audacity",
      name: "Audacity",
      officialUrl: "https://www.audacityteam.org/",
      description: "Free, open source, cross-platform audio software for multi-track recording and editing.",
      category: "Audio",
      freePlanType: "OPEN_SOURCE",
      limitations: "Requires local installation; interface has a learning curve.",
      commercialUse: "Allowed under GNU GPL v2/v3",
      license: "GPL-2.0",
      osSupport: "Windows, macOS, Linux",
      isLocal: true,
      apiAvailable: false,
      confidenceScore: 98,
    },
    {
      slug: "blender",
      name: "Blender",
      officialUrl: "https://www.blender.org/",
      description: "Free and open source 3D creation suite supporting modeling, rigging, animation, and rendering.",
      category: "Design",
      freePlanType: "OPEN_SOURCE",
      limitations: "Hardware intensive for complex 3D renders; steep learning curve.",
      commercialUse: "Allowed without royalty",
      license: "GPL-3.0",
      osSupport: "Windows, macOS, Linux",
      isLocal: true,
      apiAvailable: true,
      confidenceScore: 99,
    },
    {
      slug: "canva-free",
      name: "Canva (Free Tier)",
      officialUrl: "https://www.canva.com/",
      description: "Cloud-based graphic design platform with thousands of free templates, fonts, and stock media.",
      category: "Design",
      freePlanType: "FREEMIUM",
      limitations: "Premium stock elements watermarked; 5GB cloud storage cap.",
      commercialUse: "Allowed for original designs using free elements",
      license: "Proprietary",
      osSupport: "Web, iOS, Android",
      isLocal: false,
      apiAvailable: true,
      confidenceScore: 95,
    },
    {
      slug: "ollama",
      name: "Ollama",
      officialUrl: "https://ollama.com/",
      description: "Get up and running with large language models locally on your PC (Llama 3, Mistral, Gemma).",
      category: "Coding",
      freePlanType: "OPEN_SOURCE",
      limitations: "Requires 8GB+ RAM for 7B/8B models; GPU recommended for fast inference.",
      commercialUse: "Subject to individual model weights (e.g. Llama 3 license)",
      license: "MIT",
      osSupport: "macOS, Linux, Windows",
      isLocal: true,
      apiAvailable: true,
      confidenceScore: 96,
    },
    {
      slug: "huggingface-spaces",
      name: "Hugging Face Spaces",
      officialUrl: "https://huggingface.co/spaces",
      description: "Host ML demo apps on free community CPU hardware using Gradio and Streamlit.",
      category: "Web",
      freePlanType: "FREE_WITH_LIMITS",
      limitations: "Free CPU: 2 vCPU, 16GB RAM; sleeps after inactivity.",
      commercialUse: "Allowed under community guidelines",
      license: "Apache-2.0",
      osSupport: "Web",
      isLocal: false,
      apiAvailable: true,
      confidenceScore: 94,
    },
    {
      slug: "vscode",
      name: "Visual Studio Code",
      officialUrl: "https://code.visualstudio.com/",
      description: "Free, lightweight source-code editor running on your desktop with thousands of free extensions.",
      category: "Coding",
      freePlanType: "FREE",
      limitations: "Requires manual extension configuration for language support.",
      commercialUse: "Free for commercial and non-commercial use",
      license: "MIT (Code - OSS)",
      osSupport: "Windows, macOS, Linux",
      isLocal: true,
      apiAvailable: true,
      confidenceScore: 99,
    },
    {
      slug: "capcut-web",
      name: "CapCut Web (Free Tier)",
      officialUrl: "https://www.capcut.com/",
      description: "Browser-based video editor with automated auto-captions, transcript generation, and transitions.",
      category: "Video",
      freePlanType: "FREEMIUM",
      limitations: "Some transitions and filters are Pro; export limit 1080p on free tier.",
      commercialUse: "Allowed for personal and freelance content creations",
      license: "Proprietary",
      osSupport: "Web, Windows, macOS",
      isLocal: false,
      apiAvailable: false,
      confidenceScore: 90,
    },
    {
      slug: "google-colab",
      name: "Google Colab",
      officialUrl: "https://colab.research.google.com/",
      description: "Hosted Jupyter notebook service providing free access to computing resources including GPUs.",
      category: "Coding",
      freePlanType: "FREE_WITH_LIMITS",
      limitations: "Timeouts after 12 hours or disconnects; usage limits apply dynamically.",
      commercialUse: "Permitted under Google Cloud Terms",
      license: "Proprietary",
      osSupport: "Web",
      isLocal: false,
      apiAvailable: false,
      confidenceScore: 93,
    },
    {
      slug: "supabase-free",
      name: "Supabase (Free Tier)",
      officialUrl: "https://supabase.com/",
      description: "Open source Firebase alternative: free PostgreSQL database, authentication, and instant REST APIs.",
      category: "Web",
      freePlanType: "FREEMIUM",
      limitations: "2 free projects, 500MB database, pauses after 1 week of inactivity.",
      commercialUse: "Full commercial use allowed",
      license: "Apache-2.0",
      osSupport: "Web",
      isLocal: false,
      apiAvailable: true,
      confidenceScore: 97,
    },
    {
      slug: "appsmith",
      name: "Appsmith Community",
      officialUrl: "https://www.appsmith.com/",
      description: "Low-code open-source platform to build internal dashboards, admin panels, and CRUD apps.",
      category: "Automation",
      freePlanType: "OPEN_SOURCE",
      limitations: "Self-hosted requires Docker or cloud instance; cloud free tier has seat limits.",
      commercialUse: "Allowed under Apache 2.0 license",
      license: "Apache-2.0",
      osSupport: "Web, Docker",
      isLocal: false,
      apiAvailable: true,
      confidenceScore: 92,
    },
  ];

  const createdTools: Record<string, any> = {};
  for (const t of toolsData) {
    const tool = await prisma.aITool.create({
      data: {
        ...t,
        sources: {
          create: {
            url: t.officialUrl,
            sourceName: `${t.name} Official Website & Documentation`,
            reliabilityTier: 1,
            citationSnippet: `Verified official free tier and commercial terms on ${t.officialUrl}`,
          },
        },
      },
    });
    createdTools[t.slug] = tool;
  }

  // 4. Create 10 Curated Opportunities
  const oppsData = [
    {
      slug: "short-form-video-repurposing",
      title: "Short-Form Video Repurposing for Local Businesses",
      description: "Transform lengthy podcast episodes, webinars, or owner interviews into punchy TikTok/Reels with auto-captions and hook titles using free tools.",
      category: "FREELANCE",
      targetMarket: "Local real estate agents, fitness coaches, podcasters, plumbers",
      customerProblem: "Business owners have raw video but lack time or software to edit 30-second clips.",
      estimatedHoursMin: 3,
      estimatedHoursMax: 6,
      difficulty: "BEGINNER",
      potentialRevenueMinCents: 5000, // $50
      potentialRevenueMaxCents: 30000, // $300
      revenueModel: "SERVICE_FEE",
      opportunityScore: 88,
      riskScore: 18,
      confidenceScore: 92,
    },
    {
      slug: "canva-digital-template-packs",
      title: "Custom Digital Template Packs for Etsy / Gumroad",
      description: "Design niche-specific business template bundles (client intake forms, invoices, social media packs) using Canva Free and sell as instant downloads.",
      category: "CREATE",
      targetMarket: "Freelancers, wedding planners, yoga instructors, small gyms",
      customerProblem: "Solo entrepreneurs need professional branding documents without hiring an agency.",
      estimatedHoursMin: 4,
      estimatedHoursMax: 8,
      difficulty: "BEGINNER",
      potentialRevenueMinCents: 1500, // $15
      potentialRevenueMaxCents: 100000, // $1,000+
      revenueModel: "DIGITAL_PRODUCT",
      opportunityScore: 84,
      riskScore: 22,
      confidenceScore: 90,
    },
    {
      slug: "local-service-landing-page",
      title: "Fast Landing Page Setup for Service Contractors",
      description: "Create a modern, high-converting one-page portfolio website for local contractors using free static hosting and template builders.",
      category: "BUILD",
      targetMarket: "Electricians, landscaping services, mobile car detailers",
      customerProblem: "Contractors rely on word of mouth or ugly Facebook pages; they lose customers without a clear booking page.",
      estimatedHoursMin: 4,
      estimatedHoursMax: 10,
      difficulty: "BEGINNER",
      potentialRevenueMinCents: 15000, // $150
      potentialRevenueMaxCents: 75000, // $750
      revenueModel: "FREELANCE_PROJECT",
      opportunityScore: 86,
      riskScore: 20,
      confidenceScore: 89,
    },
    {
      slug: "podcast-audio-restoration",
      title: "Podcast Audio Cleanup & Noise Reduction Service",
      description: "Use Audacity to remove hiss, background rumble, and mouth clicks from raw audio files to deliver broadcast-ready MP3s.",
      category: "FREELANCE",
      targetMarket: "Indie podcasters, interviewers, course creators",
      customerProblem: "Amateur audio recordings sound hollow and noisy, driving listeners away.",
      estimatedHoursMin: 2,
      estimatedHoursMax: 5,
      difficulty: "BEGINNER",
      potentialRevenueMinCents: 3000, // $30
      potentialRevenueMaxCents: 20000, // $200
      revenueModel: "SERVICE_FEE",
      opportunityScore: 82,
      riskScore: 15,
      confidenceScore: 94,
    },
    {
      slug: "ecommerce-inventory-tracker",
      title: "Custom Inventory & Order Tracker with Supabase & Appsmith",
      description: "Build an internal web app for small boutique retailers to track stock counts and supplier contacts without paying $100/mo SaaS fees.",
      category: "BUILD",
      targetMarket: "Independent clothing shops, antique dealers, coffee roasters",
      customerProblem: "Outgrowing chaotic Excel spreadsheets but enterprise ERP tools are far too expensive.",
      estimatedHoursMin: 6,
      estimatedHoursMax: 14,
      difficulty: "INTERMEDIATE",
      potentialRevenueMinCents: 25000, // $250
      potentialRevenueMaxCents: 120000, // $1,200
      revenueModel: "MICRO_SAAS",
      opportunityScore: 79,
      riskScore: 25,
      confidenceScore: 88,
    },
    {
      slug: "niche-curated-glossary-web",
      title: "Educational Niche Glossary Website with Ad/Affiliate Potential",
      description: "Build a focused reference site (e.g. 'Coffee Brewing Terminology' or 'Solar Energy Guide') with clear explanations and monetization links.",
      category: "CONTENT",
      targetMarket: "Hobbyists, students, purchasing researchers in specific niches",
      customerProblem: "Information is scattered across dense academic papers or low-quality forums.",
      estimatedHoursMin: 8,
      estimatedHoursMax: 20,
      difficulty: "BEGINNER",
      potentialRevenueMinCents: 1000,
      potentialRevenueMaxCents: 50000,
      revenueModel: "DIGITAL_PRODUCT",
      opportunityScore: 76,
      riskScore: 30,
      confidenceScore: 85,
    },
    {
      slug: "social-graphics-automation",
      title: "Batch Social Media Graphics Automation Service",
      description: "Generate 30 days of consistent, branded quote cards and announcement graphics for creators in under an hour.",
      category: "AUTOMATE",
      targetMarket: "Authors, newsletter creators, wellness advocates",
      customerProblem: "Consistency is hard; creating daily graphics manually causes burnout.",
      estimatedHoursMin: 2,
      estimatedHoursMax: 5,
      difficulty: "BEGINNER",
      potentialRevenueMinCents: 4000,
      potentialRevenueMaxCents: 25000,
      revenueModel: "SERVICE_FEE",
      opportunityScore: 85,
      riskScore: 18,
      confidenceScore: 91,
    },
    {
      slug: "local-seo-content-pack",
      title: "Local Business SEO Audit & Service Page Outline",
      description: "Perform structured competitive research for local businesses and generate optimized service page copy and FAQ structures.",
      category: "MARKETING",
      targetMarket: "Dentists, chiropractors, roofing contractors",
      customerProblem: "Local service websites rank poorly because they lack dedicated service pages and clear local schema.",
      estimatedHoursMin: 4,
      estimatedHoursMax: 8,
      difficulty: "BEGINNER",
      potentialRevenueMinCents: 10000,
      potentialRevenueMaxCents: 50000,
      revenueModel: "SERVICE_FEE",
      opportunityScore: 83,
      riskScore: 20,
      confidenceScore: 88,
    },
    {
      slug: "voiceover-script-preparation",
      title: "Audiobook & Video Script Prep Formatting Service",
      description: "Convert raw manuscripts and transcripts into phonetic-annotated, time-stamped reader scripts for voice actors.",
      category: "FREELANCE",
      targetMarket: "Self-published authors, corporate trainers, indie game devs",
      customerProblem: "Unformatted manuscripts result in voice talent pronunciation errors and costly re-records.",
      estimatedHoursMin: 3,
      estimatedHoursMax: 6,
      difficulty: "BEGINNER",
      potentialRevenueMinCents: 3500,
      potentialRevenueMaxCents: 20000,
      revenueModel: "SERVICE_FEE",
      opportunityScore: 78,
      riskScore: 16,
      confidenceScore: 87,
    },
    {
      slug: "local-ai-knowledge-base",
      title: "Private Document Search with Local AI (Ollama)",
      description: "Set up a private, offline semantic search assistant on a client's computer using Ollama so their internal PDFs are never uploaded to the cloud.",
      category: "BUILD",
      targetMarket: "Lawyers, accountants, medical clinics with strict privacy policies",
      customerProblem: "Want AI search over client records but strictly prohibited from using public cloud LLMs.",
      estimatedHoursMin: 5,
      estimatedHoursMax: 12,
      difficulty: "INTERMEDIATE",
      potentialRevenueMinCents: 30000,
      potentialRevenueMaxCents: 150000,
      revenueModel: "FREELANCE_PROJECT",
      opportunityScore: 81,
      riskScore: 24,
      confidenceScore: 86,
    },
  ];

  const createdOpps: Record<string, any> = {};
  for (const o of oppsData) {
    const opp = await prisma.opportunity.create({
      data: {
        ...o,
        sources: {
          create: {
            url: "https://www.upwork.com/freelance-jobs/",
            title: `Market demand analysis for ${o.title}`,
            notes: "Verified recurring client requests and active freelance proposals.",
          },
        },
        scores: {
          create: {
            beginnerFriendliness: 85,
            marketDemand: 80,
            freeToolAvailability: 90,
            monetizationClarity: 85,
            scalability: 75,
            platformRisk: o.riskScore,
            legalRisk: 10,
          },
        },
      },
    });
    createdOpps[o.slug] = opp;
  }

  // 5. Create 10 Full Missions with Step-by-Step Beginner Mode
  const missionsData = [
    {
      slug: "mission-video-repurposing",
      opportunityId: createdOpps["short-form-video-repurposing"].id,
      title: "Create 3 Viral Short Clips from a Long-Form Video",
      tagLine: "Turn any 30-minute webinar into engaging TikToks/Reels in under 2 hours.",
      description: "Learn to identify high-value audio hooks, crop for vertical aspect ratio, generate dynamic animated captions, and export ready-to-deliver clips using CapCut Web.",
      category: "FREELANCE",
      difficulty: "BEGINNER",
      estimatedTime: "2 hours",
      hardwareTier: "TIER_1_LITE",
      whyThisExists: "Content creators produce hours of video weekly but fail on short-form platforms because editing vertical clips with bold subtitles takes tedious manual labor.",
      whatYouWillBuild: "A sample portfolio of 3 vertical short clips with animated auto-captions and hook overlays, plus a ready-to-send client proposal pitch.",
      potentialMonetization: "Offer a $150/week package delivering 3 edited short clips every Monday to local podcasters or coaches.",
      riskNotes: "Ensure you obtain explicit permission or creative commons licensing before editing third-party videos.",
      toolSlugs: ["capcut-web"],
      steps: [
        {
          stepNumber: 1,
          title: "Access CapCut Web",
          objective: "Create a free account and open the web editor.",
          instruction: "Open your browser and navigate to capcut.com. Click 'Sign Up' with your email. Once logged in, select 'Create new video' and choose the '9:16' vertical aspect ratio.",
          promptTemplate: null,
          expectedOutput: "A blank 9:16 timeline canvas ready in your browser.",
          troubleshooting: "If the web editor feels slow, close extra browser tabs or disable hardware-intensive extensions.",
        },
        {
          stepNumber: 2,
          title: "Import a Royalty-Free Practice Video",
          objective: "Load a practice interview or speech file.",
          instruction: "Download a free public domain speech or interview from YouTube / Pexels. Click 'Upload' on the CapCut left toolbar and select your video file. Drag it onto Track 1.",
          promptTemplate: null,
          expectedOutput: "Video waveform and video preview visible on Track 1.",
          troubleshooting: "Ensure video is in MP4 format under 500MB for smooth web playback.",
        },
        {
          stepNumber: 3,
          title: "Identify the 30-Second Hook",
          objective: "Find the single most interesting insight in the recording.",
          instruction: "Listen through and find a statement that creates curiosity within the first 3 seconds (e.g., 'The biggest mistake people make...'). Cut the video right before this sentence and end after the key takeaway.",
          promptTemplate: "Review this transcript snippet and suggest the top 3 hook sentences: [Paste transcript]",
          expectedOutput: "A trimmed clip lasting between 25 and 50 seconds.",
          troubleshooting: "Avoid rambling introductions. Start immediately on the impactful sentence.",
        },
        {
          stepNumber: 4,
          title: "Generate Automated Captions",
          objective: "Produce synchronized text captions without typing manually.",
          instruction: "Click 'Captions' on the left menu, then select 'Auto captions'. Choose your language and click 'Generate'. Within 30 seconds, captions will appear as a text track above your video.",
          promptTemplate: null,
          expectedOutput: "Text subtitle layer synchronized with speech.",
          troubleshooting: "If words are misspelled (names, technical jargon), double-click the subtitle in the right sidebar to correct them.",
        },
        {
          stepNumber: 5,
          title: "Style the Subtitles for Retention",
          objective: "Apply high-contrast colors and dynamic text presets.",
          instruction: "Select the caption layer. In the Text styling panel, choose a bold font (such as Anton or Montserrat Bold), set fill to White or Bright Yellow, and add a 4px Black stroke outline for readability.",
          promptTemplate: null,
          expectedOutput: "Punchy, easy-to-read captions that stand out on mobile screens.",
          troubleshooting: "Make sure text is positioned in the center-middle, away from TikTok/Reels UI overlay areas.",
        },
        {
          stepNumber: 6,
          title: "Add a Hook Headline Overlay",
          objective: "Create a persistent title banner at the top of the frame.",
          instruction: "Click 'Text' -> 'Add heading'. Position it at the top 15% of the frame with a concise teaser, e.g., 'DON'T MAKE THIS MISTAKE ⚠️'.",
          promptTemplate: "Give me 5 punchy 4-word hook titles for a video about [topic]:",
          expectedOutput: "Clear headline visible throughout the video.",
          troubleshooting: "Keep the headline under 6 words so it doesn't clutter the speaker.",
        },
        {
          stepNumber: 7,
          title: "Export in 1080p Resolution",
          objective: "Download the finished vertical MP4 file.",
          instruction: "Click 'Export' in the top right corner. Select Resolution: 1080p, Frame Rate: 30fps, Quality: Higher. Click 'Export' and save to your computer.",
          promptTemplate: null,
          expectedOutput: "A high-definition vertical MP4 file on your desktop.",
          troubleshooting: "Do not select 4K or Pro-only filters to keep the export 100% free.",
        },
        {
          stepNumber: 8,
          title: "Package Your Sample Portfolio",
          objective: "Store the 3 sample clips on a shareable link.",
          instruction: "Upload your exported clips to a free Google Drive folder. Set access to 'Anyone with the link can view'.",
          promptTemplate: null,
          expectedOutput: "A public Google Drive link displaying your 3 demo clips.",
          troubleshooting: "Verify link in an incognito window to confirm anyone can watch without logging in.",
        },
        {
          stepNumber: 9,
          title: "Draft Your Outreach Pitch",
          objective: "Prepare a polite, value-first message for potential clients.",
          instruction: "Copy our sample outreach email template. Customize the recipient name and paste your Google Drive sample link.",
          promptTemplate: "Hi [Name], loved your recent video on [Topic]. I cut a 30-second vertical preview with subtitles to show how it looks for Reels/TikTok: [Link]. No charge, hope it helps your reach! If you'd like 3 of these every week, happy to chat.",
          expectedOutput: "Personalized pitch message ready to send.",
          troubleshooting: "Never spam hundreds of accounts. Send 5 tailored messages to people you actually follow.",
        },
        {
          stepNumber: 10,
          title: "Deliver & Track Your First Result",
          objective: "Send outreach and log evidence in your EarnQuest workspace.",
          instruction: "Send your pitch to 3 creators. In EarnQuest, record the links in your Project Workspace. When a client responds or orders, submit proof in the Earnings tab!",
          promptTemplate: null,
          expectedOutput: "Project logged in EarnQuest workspace with 50 XP awarded.",
          troubleshooting: "Follow up politely once after 4 days if they haven't replied.",
        },
      ],
    },
    {
      slug: "mission-canva-templates",
      opportunityId: createdOpps["canva-digital-template-packs"].id,
      title: "Design & Launch a Niche Business Template Bundle",
      tagLine: "Create a 5-template business bundle and publish it on Gumroad in 3 hours.",
      description: "Learn how to build editable Canva templates for a specific niche, generate shareable template links, and list them on a free Gumroad checkout.",
      category: "CREATE",
      difficulty: "BEGINNER",
      estimatedTime: "3 hours",
      hardwareTier: "TIER_1_LITE",
      whyThisExists: "Service providers waste hours designing client questionnaires and proposals from scratch and willingly pay $15-$30 for ready-made Canva files.",
      whatYouWillBuild: "A 5-page editable Client Welcome & Onboarding packet ready for sale with a live Gumroad purchase link.",
      potentialMonetization: "Priced at $19. Sell 10 copies/month for $190 passive digital income.",
      riskNotes: "Only use Canva Free elements and fonts. Never use Pro elements or resell Canva stock photos as standalone assets.",
      toolSlugs: ["canva-free"],
      steps: [
        {
          stepNumber: 1,
          title: "Pick Your Niche & Document Type",
          objective: "Select a focused target audience and document bundle.",
          instruction: "Choose one niche: (A) Fitness Trainers, (B) Wedding Planners, (C) Independent Photographers. Document type: Client Welcome Packet.",
          promptTemplate: null,
          expectedOutput: "Clear decision on target audience and design tone.",
          troubleshooting: "Do not choose 'everyone'. Specific niches convert 3x higher.",
        },
        {
          stepNumber: 2,
          title: "Open Canva and Set Canvas Dimensions",
          objective: "Start a blank US Letter or A4 document.",
          instruction: "Log in to canva.com. Search for 'Document A4' or 'US Letter'. Click 'Create blank'.",
          promptTemplate: null,
          expectedOutput: "Blank multi-page canvas ready in Canva.",
          troubleshooting: "Ensure document sizing is standard printable dimensions.",
        },
        {
          stepNumber: 3,
          title: "Design Page 1: Cover Page",
          objective: "Build an elegant, professional cover layout.",
          instruction: "Add a large title: 'CLIENT WELCOME PACKET', a clean subheader: '[Your Business Name]', and a minimalist placeholder photo frame.",
          promptTemplate: null,
          expectedOutput: "Polished cover page using only free fonts and geometric shapes.",
          troubleshooting: "Check element details: ensure the crown icon (Pro) is NOT present.",
        },
        {
          stepNumber: 4,
          title: "Design Page 2: Welcome & Meet the Team",
          objective: "Provide an introduction page with bio and expectations.",
          instruction: "Add a 2-column layout: Left column for a photo frame and contact info; Right column for a warm welcome letter and working hours.",
          promptTemplate: "Write a warm, professional client welcome letter for a [niche] onboarding document:",
          expectedOutput: "Structured introduction page with placeholder copy.",
          troubleshooting: "Use clear visual hierarchy: Title 28pt, Body 12pt.",
        },
        {
          stepNumber: 5,
          title: "Design Page 3: Project Roadmap & Milestones",
          objective: "Map out the 4 steps of a typical client project.",
          instruction: "Create a 4-step vertical or horizontal timeline: Phase 1 (Discovery), Phase 2 (Creation), Phase 3 (Review), Phase 4 (Delivery).",
          promptTemplate: null,
          expectedOutput: "Visual timeline graphic that clients can edit easily.",
          troubleshooting: "Keep timeline icons simple: circles or checkmarks.",
        },
        {
          stepNumber: 6,
          title: "Design Page 4 & 5: FAQ & Invoice Summary",
          objective: "Complete the document suite with essential client answers.",
          instruction: "Page 4: 5 common client questions with placeholder answers. Page 5: Invoice summary table with bank/payment details placeholder.",
          promptTemplate: "List 5 essential FAQs clients ask a [niche] provider:",
          expectedOutput: "Completed 5-page document packet.",
          troubleshooting: "Review the whole packet for consistent font pairings (e.g. Playfair Display + Lato).",
        },
        {
          stepNumber: 7,
          title: "Generate the Canva Template Link",
          objective: "Create a link that copies the design without altering your original.",
          instruction: "Click 'Share' -> 'More' -> 'Template Link'. Copy the generated URL.",
          promptTemplate: null,
          expectedOutput: "A URL starting with canva.com/design/.../view?template=...",
          troubleshooting: "Do NOT share standard view/edit link; only the Template Link creates duplicate copies for buyers.",
        },
        {
          stepNumber: 8,
          title: "Create Delivery PDF with Access Button",
          objective: "Build the 1-page PDF that customers download upon purchase.",
          instruction: "In Canva, make a simple 1-page note: 'Thank you for purchasing! Click below to access your editable Canva template'. Hyperlink a button to your Template Link. Download as 'Standard PDF'.",
          promptTemplate: null,
          expectedOutput: "A clickable delivery PDF on your computer.",
          troubleshooting: "Test the PDF by opening it in a browser and clicking the link.",
        },
        {
          stepNumber: 9,
          title: "Set Up Free Listing on Gumroad",
          objective: "Create the product listing page with price and delivery file.",
          instruction: "Sign up on gumroad.com (free account). Click 'New Product' -> 'Digital product'. Set title, price ($19), upload cover image from Canva, and attach the Delivery PDF.",
          promptTemplate: "Write a compelling 200-word Gumroad product description for a Canva client onboarding template:",
          expectedOutput: "Live, public Gumroad checkout link.",
          troubleshooting: "Remember Gumroad takes a small percentage fee per transaction, but there is zero upfront cost.",
        },
        {
          stepNumber: 10,
          title: "Record Deliverables in Workspace",
          objective: "Save your listing link in EarnQuest to earn XP.",
          instruction: "Paste your Gumroad URL into your EarnQuest Project Workspace. Congratulations, your opportunity engine is live!",
          promptTemplate: null,
          expectedOutput: "Project saved with live URL and 100 XP awarded.",
          troubleshooting: "Share the link in relevant niche Facebook or Reddit communities (adhering to community self-promo rules).",
        },
      ],
    },
    {
      slug: "mission-landing-page",
      opportunityId: createdOpps["local-service-landing-page"].id,
      title: "Build a High-Converting Local Service Landing Page",
      tagLine: "Construct a responsive 1-page booking site for a local tradesperson.",
      description: "Use free modern HTML/CSS templates or GitHub Pages static hosting to launch a responsive portfolio site for a local service contractor.",
      category: "BUILD",
      difficulty: "BEGINNER",
      estimatedTime: "4 hours",
      hardwareTier: "TIER_1_LITE",
      whyThisExists: "Over 40% of local tradespeople have no website or an outdated page that doesn't work on mobile, costing them valuable job quotes.",
      whatYouWillBuild: "A mobile-responsive one-page site with Hero, Services, Reviews, and Contact Form hosted for free.",
      potentialMonetization: "Charge $250 upfront build + optional $25/month hosting & maintenance fee.",
      riskNotes: "Clarify with the client that domain name registration ($12/yr) is purchased directly by them.",
      toolSlugs: ["vscode"],
      steps: [
        {
          stepNumber: 1,
          title: "Download a Free Tailwind HTML Template",
          objective: "Get a clean, modern responsive landing page template.",
          instruction: "Download a free open-source static landing page template (HTML/Tailwind) from HTML5 UP or Tailwind Awesome.",
          promptTemplate: null,
          expectedOutput: "Folder with index.html, styles, and asset directories.",
          troubleshooting: "Verify the template has an MIT or CC-BY license for commercial client projects.",
        },
        {
          stepNumber: 2,
          title: "Open Template in Visual Studio Code",
          objective: "Launch the project in a free code editor.",
          instruction: "Open VS Code. Click 'File' -> 'Open Folder' and select your extracted template folder.",
          promptTemplate: null,
          expectedOutput: "Project tree visible on the left sidebar.",
          troubleshooting: "Install the free 'Live Server' extension in VS Code for instant browser preview.",
        },
        {
          stepNumber: 3,
          title: "Customize the Hero Section",
          objective: "Set headline, service area, and primary call-to-action button.",
          instruction: "Edit index.html: replace placeholder heading with '[City]'s Most Reliable [Service]'. Add phone number and 'Request Free Quote' button linking to contact section.",
          promptTemplate: "Write 3 conversion-focused hero headlines for a local [trade, e.g. residential plumbing] company in [City]:",
          expectedOutput: "Clear, locally targeted hero banner visible in preview.",
          troubleshooting: "Ensure phone number uses `tel:+1234567890` format for one-tap mobile calling.",
        },
        {
          stepNumber: 4,
          title: "Add 3 Core Service Cards",
          objective: "Display what the contractor offers with clear pricing cues.",
          instruction: "Create three distinct cards: (1) Emergency Repairs, (2) Installations, (3) Routine Inspections. Add checkmarks highlighting fast response time and licensed guarantees.",
          promptTemplate: null,
          expectedOutput: "3-column grid on desktop collapsing to 1-column on mobile.",
          troubleshooting: "Check mobile view by resizing browser window to phone width.",
        },
        {
          stepNumber: 5,
          title: "Add Social Proof & Google Review Badges",
          objective: "Build trust with testimonial quotes and 5-star ratings.",
          instruction: "Insert 3 testimonial quote cards with customer first names and neighborhood areas.",
          promptTemplate: null,
          expectedOutput: "Trust section showing real customer praise.",
          troubleshooting: "Always use real client reviews from their Google Business profile with their permission.",
        },
        {
          stepNumber: 6,
          title: "Configure Free Contact Form via Formspree",
          objective: "Enable website inquiries to forward directly to client's email.",
          instruction: "Create a free account on formspree.io. Create a new form, copy your unique form endpoint URL, and paste it into the HTML `<form action='https://formspree.io/f/YOUR_ID' method='POST'>`.",
          promptTemplate: null,
          expectedOutput: "Working form sending real email notifications.",
          troubleshooting: "Formspree free tier includes 50 submissions/month—plenty for a local contractor.",
        },
        {
          stepNumber: 7,
          title: "Deploy for Free on GitHub Pages or Vercel",
          objective: "Publish the static website to a live public URL.",
          instruction: "Push the project to a public GitHub repository and enable GitHub Pages, or drag-and-drop the folder into Vercel Free.",
          promptTemplate: null,
          expectedOutput: "A live, secure HTTPS URL (e.g., https://your-project.vercel.app).",
          troubleshooting: "Confirm HTTPS padlock is green and form submissions arrive successfully.",
        },
        {
          stepNumber: 8,
          title: "Audit Mobile Speed with Google PageSpeed",
          objective: "Verify the site loads in under 2 seconds.",
          instruction: "Run your live URL through pagespeed.web.dev. Aim for 90+ score on mobile.",
          promptTemplate: null,
          expectedOutput: "Green performance metrics proving quality to the client.",
          troubleshooting: "Compress large image files with squoosh.app if mobile score is below 85.",
        },
        {
          stepNumber: 9,
          title: "Create Presentation Deck for Local Outreach",
          objective: "Take 3 screenshots and package into a 1-page proposal.",
          instruction: "Assemble before/after mockup of the contractor's current online presence vs your new fast site.",
          promptTemplate: "Draft a polite email to a local contractor showing a free preview of their new mobile site:",
          expectedOutput: "Ready-to-send proposal email.",
          troubleshooting: "Never criticize their current site harshly; focus on how many mobile leads they'll gain.",
        },
        {
          stepNumber: 10,
          title: "Save Project & Log Outreach",
          objective: "Log your live demo URL in EarnQuest.",
          instruction: "Save your live demo URL in EarnQuest Project Workspace. Earn 150 XP and unlock Builder status!",
          promptTemplate: null,
          expectedOutput: "Project saved and verified in EarnQuest.",
          troubleshooting: "Once a client pays, submit evidence in the Earnings tab.",
        },
      ],
    },
    {
      slug: "mission-audio-cleanup",
      opportunityId: createdOpps["podcast-audio-restoration"].id,
      title: "Audio Cleanup: Remove Hiss & Echo from Voice Tracks",
      tagLine: "Use Audacity to turn amateur podcast audio into studio-quality sound.",
      description: "Master multi-band noise reduction, equalization curves, and dynamic compression to rescue muffled audio recordings.",
      category: "FREELANCE",
      difficulty: "BEGINNER",
      estimatedTime: "2 hours",
      hardwareTier: "TIER_1_LITE",
      whyThisExists: "Remote interviews recorded over Zoom or low-end microphones suffer from fan noise, room echo, and uneven volumes.",
      whatYouWillBuild: "A before-and-after audio showcase demonstrating noise removal, vocal clarity, and loudness normalization.",
      potentialMonetization: "Charge $25 per 30 minutes of processed audio on Fiverr or direct podcast outreach.",
      riskNotes: "Over-applying noise reduction creates metallic robotic artifacts. Always preview before committing.",
      toolSlugs: ["audacity"],
      steps: [
        {
          stepNumber: 1,
          title: "Install and Open Audacity",
          objective: "Download the free open source audio editor.",
          instruction: "Download Audacity from audacityteam.org and launch the program. It is 100% free and open-source.",
          promptTemplate: null,
          expectedOutput: "Audacity main window open on your screen.",
          troubleshooting: "On macOS, grant Audacity microphone permissions if prompted.",
        },
        {
          stepNumber: 2,
          title: "Import Sample Noisy Track",
          objective: "Load a practice voice recording with background hiss.",
          instruction: "Drag an MP3 or WAV file into Audacity. You will see a blue waveform.",
          promptTemplate: null,
          expectedOutput: "Audio track visible with timeline across the top.",
          troubleshooting: "Press Spacebar to play/pause audio.",
        },
        {
          stepNumber: 3,
          title: "Capture Noise Profile",
          objective: "Teach the software what background noise sounds like.",
          instruction: "Highlight 2 seconds of silence where only background hiss or room rumble is playing. Go to Effect -> Noise Removal and Repair -> Noise Reduction -> click 'Get Noise Profile'.",
          promptTemplate: null,
          expectedOutput: "Noise profile captured into memory.",
          troubleshooting: "Ensure no speaking happens in the selected 2 seconds.",
        },
        {
          stepNumber: 4,
          title: "Apply Noise Reduction",
          objective: "Remove the background hiss across the entire track.",
          instruction: "Select the entire track (Ctrl+A / Cmd+A). Return to Effect -> Noise Reduction. Set Noise Reduction to 12 dB, Sensitivity to 6, Frequency Smoothing to 3. Click OK.",
          promptTemplate: null,
          expectedOutput: "Silent portions become flat lines with zero hiss.",
          troubleshooting: "If voice sounds hollow, reduce Noise Reduction from 12 dB to 8 dB.",
        },
        {
          stepNumber: 5,
          title: "High-Pass Filter Room Rumble",
          objective: "Eliminate low-frequency air conditioner or microphone thuds.",
          instruction: "Select all. Go to Effect -> EQ and Filters -> High-Pass Filter. Set cutoff to 80 Hz with 12 dB rolloff. Click OK.",
          promptTemplate: null,
          expectedOutput: "Cleaner low end with zero muddy rumble.",
          troubleshooting: "Do not set cutoff above 100 Hz, or male voices will lose body.",
        },
        {
          stepNumber: 6,
          title: "Apply Compressor for Consistent Volume",
          objective: "Balance quiet whispers and loud laughs.",
          instruction: "Select all. Effect -> Volume and Compression -> Compressor. Set Threshold to -14 dB, Noise Floor to -40 dB, Ratio to 2.5:1. Click OK.",
          promptTemplate: null,
          expectedOutput: "Waveform peaks become even and balanced.",
          troubleshooting: "Compression brings quiet parts up so listeners don't have to adjust volume.",
        },
        {
          stepNumber: 7,
          title: "Normalize Loudness to -16 LUFS",
          objective: "Meet standard podcast broadcast volume standards.",
          instruction: "Select all. Effect -> Volume and Compression -> Loudness Normalization. Set target to -16 LUFS (standard stereo podcast loudness).",
          promptTemplate: null,
          expectedOutput: "Loud, clear audio matching Spotify and Apple Podcasts standards.",
          troubleshooting: "Always normalize after compression, never before.",
        },
        {
          stepNumber: 8,
          title: "Export Clean Master Audio",
          objective: "Save the processed track as MP3 and WAV.",
          instruction: "File -> Export Audio. Format: MP3, Bitrate: Constant 192 kbps. Save to your desktop.",
          promptTemplate: null,
          expectedOutput: "Polished audio file ready for delivery.",
          troubleshooting: "Keep the original raw file as backup.",
        },
        {
          stepNumber: 9,
          title: "Create a 20-Second Before/After Clip",
          objective: "Produce an undeniable audio proof sample.",
          instruction: "Splice 10 seconds of the noisy raw track followed by 10 seconds of the clean track with an audio voice prompt: 'Before cleanup... After cleanup'.",
          promptTemplate: null,
          expectedOutput: "A high-impact audio demo file.",
          troubleshooting: "Host it on SoundCloud or Google Drive for public sharing.",
        },
        {
          stepNumber: 10,
          title: "Post Your Service Offer",
          objective: "Publish your audio cleanup service on freelance boards.",
          instruction: "List your service offer on Fiverr, Upwork, or reach out to 3 indie podcasters directly with your before/after demo clip.",
          promptTemplate: "Hey [Host], love the show! Noticed some background AC hum on episode [X]. I made a 15-second clean version showing how crisp it could sound: [Link]. Happy to clean up your next episode for free so you can hear the difference!",
          expectedOutput: "Outreach logged in EarnQuest workspace.",
          troubleshooting: "Free first-episode trials convert into recurring monthly retainers over 40% of the time.",
        },
      ],
    },
    {
      slug: "mission-ecommerce-tracker",
      opportunityId: createdOpps["ecommerce-inventory-tracker"].id,
      title: "Build an Inventory Web Tool with Supabase & Appsmith",
      tagLine: "Deploy an internal business app for a shop owner without writing backend code.",
      description: "Connect a free Supabase Postgres database with an Appsmith low-code frontend to track products, stock alerts, and orders.",
      category: "BUILD",
      difficulty: "INTERMEDIATE",
      estimatedTime: "5 hours",
      hardwareTier: "TIER_1_LITE",
      whyThisExists: "Small retail owners juggle spreadsheets that corrupt and cause stockouts, but commercial inventory software costs thousands annually.",
      whatYouWillBuild: "A password-protected inventory manager with Low Stock Alerts, Add Product Form, and barcode/SKU search.",
      potentialMonetization: "Charge $400 for initial setup and $50/month ongoing support.",
      riskNotes: "Ensure you give the client their own master Supabase credentials so they retain ownership of their data.",
      toolSlugs: ["supabase-free", "appsmith"],
      steps: [
        {
          stepNumber: 1,
          title: "Create Free Supabase Project",
          objective: "Provision a free cloud PostgreSQL database.",
          instruction: "Sign up at supabase.com. Click 'New Project', choose a name and secure database password. Wait 2 minutes for database provisioning.",
          promptTemplate: null,
          expectedOutput: "Supabase dashboard ready with active database.",
          troubleshooting: "Store the database password safely in a password manager.",
        },
        {
          stepNumber: 2,
          title: "Create Products Table via SQL Editor",
          objective: "Define the database schema with essential fields.",
          instruction: "In Supabase SQL Editor, run: `CREATE TABLE products (id uuid primary key default gen_random_uuid(), name text not null, sku text unique, quantity int default 0, cost_cents int, price_cents int, min_threshold int default 5, updated_at timestamp with time zone default now());`",
          promptTemplate: null,
          expectedOutput: "Success notification and table visible in Table Editor.",
          troubleshooting: "Notice we use `cost_cents` and `price_cents` (integer minor units) rather than floating decimals!",
        },
        {
          stepNumber: 3,
          title: "Insert 5 Sample Products",
          objective: "Populate demo records for visualization.",
          instruction: "Use Table Editor to add 5 sample items (e.g. Organic Coffee Beans 1kg, SKU: COF-001, Quantity: 14, Price Cents: 1800).",
          promptTemplate: null,
          expectedOutput: "5 rows displayed in the Supabase Table Editor.",
          troubleshooting: "Include at least one item with Quantity < min_threshold to test low-stock alerts.",
        },
        {
          stepNumber: 4,
          title: "Sign Up for Appsmith Community",
          objective: "Access the free low-code web app builder.",
          instruction: "Go to appsmith.com, create a free community account, and create a new application named 'Store Inventory Hub'.",
          promptTemplate: null,
          expectedOutput: "Empty Appsmith canvas with widget library.",
          troubleshooting: "Appsmith runs completely in your browser with zero local software required.",
        },
        {
          stepNumber: 5,
          title: "Connect Supabase Database Datasource",
          objective: "Link your Appsmith app to your live PostgreSQL database.",
          instruction: "In Appsmith, click 'Datasources' -> 'New' -> 'PostgreSQL'. Copy connection details from Supabase Project Settings -> Database -> Connection Info.",
          promptTemplate: null,
          expectedOutput: "'Connection successful' status in Appsmith.",
          troubleshooting: "Ensure SSL Mode is set to 'Require' as required by Supabase.",
        },
        {
          stepNumber: 6,
          title: "Build Products Table View Widget",
          objective: "Display products in a searchable, sortable data table.",
          instruction: "Drag a 'Table' widget onto the Appsmith canvas. In the query builder, write: `SELECT * FROM products ORDER BY name ASC;`. Bind query to the table.",
          promptTemplate: null,
          expectedOutput: "Interactive table displaying live database records.",
          troubleshooting: "Configure column formatting in Appsmith to format cents as currency (e.g. `$ {{ (currentRow.price_cents / 100).toFixed(2) }}`).",
        },
        {
          stepNumber: 7,
          title: "Add 'Restock Alert' Visual Indicator",
          objective: "Highlight rows in red when stock is below threshold.",
          instruction: "In the Table widget properties, set cell background color logic: `{{ currentRow.quantity <= currentRow.min_threshold ? '#fee2e2' : '#ffffff' }}`.",
          promptTemplate: null,
          expectedOutput: "Low stock items highlighted automatically in soft red.",
          troubleshooting: "This visual alert is the #1 feature small business owners love.",
        },
        {
          stepNumber: 8,
          title: "Build 'Add New Product' Modal Form",
          objective: "Allow store managers to input new items without touching SQL.",
          instruction: "Drag a Button labeled 'Add Item'. Set onClick to open a Modal with inputs for Name, SKU, Quantity, and Price. Connect the form submission to an INSERT query.",
          promptTemplate: null,
          expectedOutput: "Working form that refreshes table immediately after submission.",
          troubleshooting: "Add client-side validation to ensure SKU is not empty.",
        },
        {
          stepNumber: 9,
          title: "Deploy App & Configure Access Controls",
          objective: "Publish the web application with a secure shareable URL.",
          instruction: "Click 'Deploy' in the top right. Invite the client's email with 'Viewer/Editor' role so they can log in securely.",
          promptTemplate: null,
          expectedOutput: "A live, production-ready internal tool running in the cloud.",
          troubleshooting: "Verify the deployed URL works on mobile tablet browsers as well.",
        },
        {
          stepNumber: 10,
          title: "Document & Log in EarnQuest",
          objective: "Save demo credentials and video walkthrough in your workspace.",
          instruction: "Record a 60-second screen demo of the app in action. Paste the link into your EarnQuest Project Workspace to claim 200 XP!",
          promptTemplate: null,
          expectedOutput: "Mission completed and verified in EarnQuest.",
          troubleshooting: "Pitch this prototype to 3 local retailers who currently use pen and paper.",
        },
      ],
    },
    // Missions 6 to 10 with realistic workflows
    {
      slug: "mission-glossary-web",
      opportunityId: createdOpps["niche-curated-glossary-web"].id,
      title: "Publish an Interactive Niche Knowledge Base Site",
      tagLine: "Deploy a static search-enabled glossary site using free tools in 4 hours.",
      description: "Build an SEO-optimized terminology reference website with interactive instant search using lightweight JavaScript and GitHub Pages.",
      category: "CONTENT",
      difficulty: "BEGINNER",
      estimatedTime: "4 hours",
      hardwareTier: "TIER_1_LITE",
      whyThisExists: "Specific industries (Renewable Energy, Web3, Specialty Coffee) have jargon that confuses buyers, creating high search volume for glossary definitions.",
      whatYouWillBuild: "A 50-term searchable glossary web portal with affiliate banner placeholders.",
      potentialMonetization: "Affiliate recommendations and ad monetization as search traffic grows.",
      riskNotes: "Write original definitions. Never copy-paste text directly from Wikipedia.",
      toolSlugs: ["vscode"],
      steps: [
        {
          stepNumber: 1,
          title: "Choose a Profitable Niche",
          objective: "Pick a topic with high consumer purchase intent.",
          instruction: "Select one: (A) Solar Energy & Home Battery Tech, (B) Specialty Espresso & Coffee Brewing, (C) Remote Work Ergonomics.",
          promptTemplate: null,
          expectedOutput: "Target niche selected with defined keyword intent.",
          troubleshooting: "Focus on topics where people buy physical equipment.",
        },
        {
          stepNumber: 2,
          title: "Generate 50 Key Industry Terms",
          objective: "Create the core terminology data structure.",
          instruction: "Draft a JSON array containing 50 objects with `term`, `category`, `definition`, and `example`.",
          promptTemplate: "Generate 25 essential technical terms with clear 2-sentence beginner definitions for [niche] in JSON format:",
          expectedOutput: "Valid `terms.json` file on your computer.",
          troubleshooting: "Validate JSON syntax with a free JSON validator.",
        },
        {
          stepNumber: 3,
          title: "Build the Static Search Interface",
          objective: "Create an instant client-side filter input.",
          instruction: "Build an index.html file with a prominent search input that filters cards in real time as the user types.",
          promptTemplate: null,
          expectedOutput: "Fast instant-search response with zero server delay.",
          troubleshooting: "Keep the search input autofocus on page load.",
        },
        {
          stepNumber: 4,
          title: "Add Term Detail Cards",
          objective: "Display definitions with copyable links.",
          instruction: "Render each term inside a clean card with an anchor tag so users can share direct links (e.g., `#inverter-efficiency`).",
          promptTemplate: null,
          expectedOutput: "50 accessible, beautifully formatted glossary cards.",
          troubleshooting: "Add a subtle 'Copy Link' button on each card.",
        },
        {
          stepNumber: 5,
          title: "Insert Affiliate Resource Recommendations",
          objective: "Place compliant recommendation widgets.",
          instruction: "Under relevant definitions, add a helpful note: 'Recommended gear: [Product]'.",
          promptTemplate: null,
          expectedOutput: "Affiliate link blocks integrated naturally into educational copy.",
          troubleshooting: "Always include required affiliate disclosure: 'Earns commission from qualifying purchases'.",
        },
        {
          stepNumber: 6,
          title: "Deploy to GitHub Pages",
          objective: "Publish live on the web at zero cost.",
          instruction: "Push to GitHub and enable Pages under repository settings.",
          promptTemplate: null,
          expectedOutput: "Live URL on github.io.",
          troubleshooting: "Ensure repository has an `index.html` at the root level.",
        },
        {
          stepNumber: 7,
          title: "Submit to Google Search Console",
          objective: "Index the new educational pages in search engines.",
          instruction: "Verify your domain on search.google.com and submit your sitemap.",
          promptTemplate: null,
          expectedOutput: "Pages submitted for Google indexing.",
          troubleshooting: "Indexing usually takes 3 to 7 days for new domains.",
        },
        {
          stepNumber: 8,
          title: "Share on Niche Forums",
          objective: "Drive initial human visitors and feedback.",
          instruction: "Post a genuinely helpful link in relevant Reddit subreddits or Discord channels asking for term suggestions.",
          promptTemplate: null,
          expectedOutput: "First 50 organic visitors tracked in analytics.",
          troubleshooting: "Ask: 'What terms did I miss?' to encourage constructive engagement.",
        },
        {
          stepNumber: 9,
          title: "Add Community Term Suggestion Form",
          objective: "Allow visitors to suggest new vocabulary words.",
          instruction: "Add a simple Formspree form at the bottom: 'Suggest a term'.",
          promptTemplate: null,
          expectedOutput: "Continuous source of new search terms from your audience.",
          troubleshooting: "Check submissions weekly to keep the site fresh.",
        },
        {
          stepNumber: 10,
          title: "Log Project in EarnQuest",
          objective: "Document your live site and earn XP.",
          instruction: "Add your live website link to EarnQuest workspace and earn 120 XP.",
          promptTemplate: null,
          expectedOutput: "Project verified in EarnQuest.",
          troubleshooting: "Monitor search traffic growth in Google Search Console.",
        },
      ],
    },
    {
      slug: "mission-social-automation",
      opportunityId: createdOpps["social-graphics-automation"].id,
      title: "Batch Create 30 Branded Social Posts in 1 Hour",
      tagLine: "Use Canva Bulk Create with CSV data to generate a month of content.",
      description: "Learn how to format spreadsheets and bind data columns to Canva templates to export 30 high-impact social media quotes automatically.",
      category: "AUTOMATE",
      difficulty: "BEGINNER",
      estimatedTime: "1.5 hours",
      hardwareTier: "TIER_1_LITE",
      whyThisExists: "Content creators spend hours manually duplicating graphics one by one. Automation cuts this from 6 hours to 20 minutes.",
      whatYouWillBuild: "A 30-graphic branded carousel and quote pack ready for client delivery.",
      potentialMonetization: "Offer a $100/month 'Daily Social Graphics' subscription to solo consultants.",
      riskNotes: "Ensure quotes and tips are proofread before running bulk automation.",
      toolSlugs: ["canva-free"],
      steps: [
        {
          stepNumber: 1,
          title: "Gather 30 Industry Tips or Quotes",
          objective: "Assemble content into a spreadsheet.",
          instruction: "Create a Google Sheet with columns: `TipNumber`, `Hook`, `Body`, `Author`.",
          promptTemplate: "Generate 30 actionable, punchy tips about [topic] in a table with columns Hook, Body, and Takeaway:",
          expectedOutput: "Spreadsheet with 30 distinct rows of content.",
          troubleshooting: "Keep hooks under 8 words for visual impact.",
        },
        {
          stepNumber: 2,
          title: "Export Spreadsheet as CSV",
          objective: "Download data in standard comma-separated format.",
          instruction: "File -> Download -> Comma Separated Values (.csv). Save as `tips.csv`.",
          promptTemplate: null,
          expectedOutput: "A valid .csv file on your computer.",
          troubleshooting: "Ensure quotes or commas in text do not break CSV formatting.",
        },
        {
          stepNumber: 3,
          title: "Design a Master Canva Template",
          objective: "Create one single template with dynamic placeholders.",
          instruction: "Open Canva (1080x1080 Instagram Post). Create a master design with: Title placeholder, Body text placeholder, and Author avatar.",
          promptTemplate: null,
          expectedOutput: "One balanced master post design.",
          troubleshooting: "Make body text box large enough to fit your longest quote.",
        },
        {
          stepNumber: 4,
          title: "Open Canva 'Bulk Create' App",
          objective: "Connect the CSV data to your design elements.",
          instruction: "In Canva left sidebar, click 'Apps' -> search for 'Bulk Create' -> select 'Upload CSV'. Choose your `tips.csv`.",
          promptTemplate: null,
          expectedOutput: "Columns from CSV mapped to data fields in Canva.",
          troubleshooting: "Bulk Create is available on Canva free tier for standard text fields.",
        },
        {
          stepNumber: 5,
          title: "Connect Data to Canvas Elements",
          objective: "Bind spreadsheet columns to text elements.",
          instruction: "Right-click your Hook text -> click 'Connect data' -> select `Hook`. Repeat for `Body` and `Author`.",
          promptTemplate: null,
          expectedOutput: "Elements labeled with `[Hook]` and `[Body]` tags.",
          troubleshooting: "A checkmark will appear next to each connected field.",
        },
        {
          stepNumber: 6,
          title: "Generate All 30 Pages with One Click",
          objective: "Automate the creation of 30 unique graphics.",
          instruction: "Click 'Continue' -> review the 30 rows -> click 'Generate 30 designs'. Canva will open a new tab with all 30 pages generated!",
          promptTemplate: null,
          expectedOutput: "30 distinct, customized pages generated in seconds.",
          troubleshooting: "Scan through all 30 pages to ensure no text overlaps.",
        },
        {
          stepNumber: 7,
          title: "Quick Visual Polish Pass",
          objective: "Adjust formatting on any long outlier sentences.",
          instruction: "Spend 5 minutes adjusting text size on any slide that runs slightly long.",
          promptTemplate: null,
          expectedOutput: "All 30 slides visually balanced and pristine.",
          troubleshooting: "Keep font size above 24pt for mobile legibility.",
        },
        {
          stepNumber: 8,
          title: "Export All Images in a ZIP File",
          objective: "Download high-res PNGs.",
          instruction: "Share -> Download -> File type: PNG -> Select all 30 pages -> Download.",
          promptTemplate: null,
          expectedOutput: "A ZIP file with 30 labeled image files.",
          troubleshooting: "Unzip the folder to inspect image quality.",
        },
        {
          stepNumber: 9,
          title: "Package Client Delivery Link",
          objective: "Prepare the deliverables for client handoff.",
          instruction: "Upload the 30 images to a client Google Drive folder organized into Week 1, Week 2, Week 3, and Week 4 subfolders.",
          promptTemplate: null,
          expectedOutput: "A tidy, professional client delivery folder.",
          troubleshooting: "Clients love organized weekly folders—it shows professionalism.",
        },
        {
          stepNumber: 10,
          title: "Log Project and Collect Payment",
          objective: "Record your automation deliverable in EarnQuest.",
          instruction: "Log the project in your EarnQuest workspace to claim 100 XP. Record client earnings in the Earnings tab once received!",
          promptTemplate: null,
          expectedOutput: "Completed mission badge and XP added.",
          troubleshooting: "Pitch this package to consultants who post inconsistently.",
        },
      ],
    },
    {
      slug: "mission-seo-audit",
      opportunityId: createdOpps["local-seo-content-pack"].id,
      title: "Deliver a Local Business SEO & Service Content Pack",
      tagLine: "Help a neighborhood service business outrank local competitors.",
      description: "Research local search competitors, identify missing service keyword pages, and write 3 high-ranking landing page copy outlines.",
      category: "MARKETING",
      difficulty: "BEGINNER",
      estimatedTime: "3 hours",
      hardwareTier: "TIER_1_LITE",
      whyThisExists: "Most local service companies rank only for their brand name and lose dozens of high-intent searchers looking for specific services in their area.",
      whatYouWillBuild: "A 4-page Local SEO Opportunity Audit with 3 keyword-optimized service page drafts ready for publication.",
      potentialMonetization: "Charge $175 for the audit and copy package.",
      riskNotes: "Do not guarantee #1 rankings. Emphasize organic search visibility and clear customer information.",
      toolSlugs: ["vscode"],
      steps: [
        {
          stepNumber: 1,
          title: "Select a Local Business Category",
          objective: "Choose an industry with high search volume.",
          instruction: "Pick: (A) Emergency Plumber in [City], (B) Residential Painter in [City], (C) Tree Trimming Service in [City].",
          promptTemplate: null,
          expectedOutput: "Defined target business type and geographic region.",
          troubleshooting: "Choose mid-sized cities (100k - 500k population) for optimal opportunity.",
        },
        {
          stepNumber: 2,
          title: "Inspect the Top 3 Ranking Competitors",
          objective: "Analyze what top-ranked Google Map and organic sites do well.",
          instruction: "Search '[service] [city]' in an incognito browser. Note the top 3 organic websites and list their menu service pages.",
          promptTemplate: null,
          expectedOutput: "Notes on competitor service pages, headlines, and review counts.",
          troubleshooting: "Ignore national aggregator sites like Yelp or Angi; look at actual local business websites.",
        },
        {
          stepNumber: 3,
          title: "Find Missing High-Intent Service Keywords",
          objective: "Identify searches competitors are winning that your client lacks.",
          instruction: "Use Google Autocomplete and 'People Also Ask' to list 5 specific service keywords (e.g., 'water heater replacement [city]').",
          promptTemplate: "Analyze these competitor pages and list 5 high-intent search queries a local customer has before hiring: [Competitor info]",
          expectedOutput: "List of 5 high-value search terms.",
          troubleshooting: "Focus on emergency or specific repair terms—they convert highest.",
        },
        {
          stepNumber: 4,
          title: "Draft Service Page 1: Hero & Local Trust",
          objective: "Write high-converting headline and local area confirmation.",
          instruction: "Write: Exact H1 match with city, 3 bullet guarantees (Licensed, Same-Day, Transparent Pricing), and clear phone CTA.",
          promptTemplate: "Write a high-converting local service page hero section for [service] in [city]:",
          expectedOutput: "Hero section copy tailored to the client's city.",
          troubleshooting: "Mention local landmarks or neighborhoods to build immediate trust.",
        },
        {
          stepNumber: 5,
          title: "Draft Service Page 2: Step-by-Step Process",
          objective: "Explain how service calls work to remove customer anxiety.",
          instruction: "Draft: (1) Free Initial Consultation, (2) Upfront Written Estimate, (3) Clean On-Site Execution, (4) Final Quality Check.",
          promptTemplate: null,
          expectedOutput: "Clear 4-step customer journey section.",
          troubleshooting: "Emphasize clean-up and respectful treatment of client homes.",
        },
        {
          stepNumber: 6,
          title: "Draft Service Page 3: 5 Local FAQs with Schema",
          objective: "Answer common questions to win featured snippets.",
          instruction: "Write 5 common questions: cost estimates, response time, warranties, permits required, and insurance coverage.",
          promptTemplate: "Draft 5 informative FAQs for homeowners hiring a [service] in [city]:",
          expectedOutput: "Complete FAQ section ready for website upload.",
          troubleshooting: "Keep answers direct and helpful (under 3 sentences each).",
        },
        {
          stepNumber: 7,
          title: "Package into a Clean Client Audit Document",
          objective: "Assemble findings into a professional PDF report.",
          instruction: "Use Canva Free or Google Docs to format into a clean 'Local SEO Growth Plan' report with client's logo.",
          promptTemplate: null,
          expectedOutput: "A polished 4-page proposal document.",
          troubleshooting: "Use clean charts or bullet points rather than dense walls of text.",
        },
        {
          stepNumber: 8,
          title: "Identify 5 Outreach Prospects",
          objective: "Find 5 local companies ranking on page 2 or 3 of Google.",
          instruction: "Find 5 local business owners who have good reviews (4+ stars) but an outdated website with zero dedicated service pages.",
          promptTemplate: null,
          expectedOutput: "List of 5 business owner names and contact emails.",
          troubleshooting: "Check their website footer or Facebook page for owner names.",
        },
        {
          stepNumber: 9,
          title: "Send Value-First Video or PDF Teaser",
          objective: "Send a polite teaser highlighting one quick fix.",
          instruction: "Send a brief note: 'Hey [Name], noticed your plumbing company ranks well on Google Maps, but you're missing out on searches for 'tankless water heater repair'. Made a free outline showing how to capture those calls: [Link]'.",
          promptTemplate: null,
          expectedOutput: "Outreach sent to 5 prospects.",
          troubleshooting: "Never sound automated; reference a real recent job from their photos.",
        },
        {
          stepNumber: 10,
          title: "Log Outreach & Close Client",
          objective: "Track progress in EarnQuest.",
          instruction: "Record your outreach in your EarnQuest workspace. When a client books, submit your proof in the Earnings tab to verify your revenue!",
          promptTemplate: null,
          expectedOutput: "150 XP awarded and project progress updated.",
          troubleshooting: "Offer to publish the pages directly onto their WordPress/Squarespace site for an extra fee.",
        },
      ],
    },
    {
      slug: "mission-voiceover-prep",
      opportunityId: createdOpps["voiceover-script-preparation"].id,
      title: "Format Audio Scripts & Phonetic Guides for Narrators",
      tagLine: "Prepare clean, mistake-free reader scripts for audiobook narrators.",
      description: "Convert raw manuscripts into time-stamped, phonetically annotated narrator scripts that prevent expensive studio re-takes.",
      category: "FREELANCE",
      difficulty: "BEGINNER",
      estimatedTime: "2.5 hours",
      hardwareTier: "TIER_1_LITE",
      whyThisExists: "Voice actors waste hours researching complex pronunciations (character names, medical terms) and gladly pay for cleanly annotated scripts.",
      whatYouWillBuild: "A 10-chapter formatted narrator script with character voice notes and pronunciation glossary.",
      potentialMonetization: "Charge $50 to $150 per book formatted.",
      riskNotes: "Cross-check pronunciations using official dictionaries or author notes.",
      toolSlugs: ["vscode"],
      steps: [
        {
          stepNumber: 1,
          title: "Receive Manuscript and Identify Complex Terms",
          objective: "Scan the text for names, foreign phrases, and technical words.",
          instruction: "Paste chapter text into your editor. Search for capital letters and unfamiliar jargon.",
          promptTemplate: "Scan this text and extract all character names, fantasy terms, and technical words needing phonetic spelling: [Paste text]",
          expectedOutput: "Glossary table with all unique terms.",
          troubleshooting: "Confirm character accents or dialects with author upfront.",
        },
        {
          stepNumber: 2,
          title: "Add Phonetic Respellings",
          objective: "Provide clear phonetic pronunciation cues.",
          instruction: "Next to each term, provide intuitive phonetics (e.g., 'Hermione: her-MY-oh-nee').",
          promptTemplate: null,
          expectedOutput: "Complete pronunciation guide table.",
          troubleshooting: "Use simple capitalized emphasis syllables rather than complex IPA symbols.",
        },
        {
          stepNumber: 3,
          title: "Format Script with Line Spacing for Reading",
          objective: "Optimize the layout for recording booth tablets.",
          instruction: "Format in 1.5 line spacing, 14pt readable font (e.g. Georgia or Arial), with wide margins.",
          promptTemplate: null,
          expectedOutput: "Clean, non-distracting reading script.",
          troubleshooting: "Never use small fonts or dense paragraphs in recording scripts.",
        },
        {
          stepNumber: 4,
          title: "Add Character Dialogue Tags & Tone Cues",
          objective: "Highlight speaker transitions clearly.",
          instruction: "Bold character names before dialogue and add brief emotion tags: `[whispering]`, `[angry]`.",
          promptTemplate: null,
          expectedOutput: "Dialogue passages clearly distinguishable from narration.",
          troubleshooting: "Use color coding (e.g. blue for protagonist) if client requests.",
        },
        {
          stepNumber: 5,
          title: "Export Final PDF and Audio Guide",
          objective: "Package clean delivery file for the voice talent.",
          instruction: "Export as PDF with bookmarks for each chapter.",
          promptTemplate: null,
          expectedOutput: "Polished, bookmarked reader PDF ready for the studio.",
          troubleshooting: "Double-check page breaks don't split sentences awkwardly.",
        },
        {
          stepNumber: 6,
          title: "Package Sample Showcase",
          objective: "Create a 2-page before/after demo for marketing.",
          instruction: "Create a side-by-side comparison showing raw manuscript vs your booth-ready annotated script.",
          promptTemplate: null,
          expectedOutput: "Marketing sample ready to share.",
          troubleshooting: "Blur out proprietary book plot details in public samples.",
        },
        {
          stepNumber: 7,
          title: "Post Offer in Voice Actor & Indie Author Communities",
          objective: "Connect with narrators on ACX and Reddit.",
          instruction: "Share your service in r/VoiceActing or indie author formatting forums.",
          promptTemplate: null,
          expectedOutput: "Active service listing with sample proof.",
          troubleshooting: "Always respect forum rules on promotional posts.",
        },
        {
          stepNumber: 8,
          title: "Complete Order & Deliver Revisions",
          objective: "Deliver project and handle any author pronunciation queries.",
          instruction: "Deliver the completed PDF with a polite note offering 1 round of free pronunciation adjustments.",
          promptTemplate: null,
          expectedOutput: "Satisfied author/narrator client.",
          troubleshooting: "Prompt revisions build long-term repeat clientele.",
        },
        {
          stepNumber: 9,
          title: "Collect Testimonial & Payment",
          objective: "Gather feedback and verified earnings proof.",
          instruction: "Request a 1-sentence quote from the author about how much studio time your script saved.",
          promptTemplate: null,
          expectedOutput: "Verified testimonial quote.",
          troubleshooting: "Save invoice receipt for EarnQuest verification.",
        },
        {
          stepNumber: 10,
          title: "Log Earnings in EarnQuest",
          objective: "Record revenue and earn XP.",
          instruction: "Submit your payment screenshot or invoice in the EarnQuest Earnings dashboard to build your verified score!",
          promptTemplate: null,
          expectedOutput: "XP awarded, profile updated, level increased.",
          troubleshooting: "Consistent $50-$100 orders compound quickly.",
        },
      ],
    },
    {
      slug: "mission-local-ai-search",
      opportunityId: createdOpps["local-ai-knowledge-base"].id,
      title: "Set Up Private Offline Document Search with Ollama",
      tagLine: "Deploy a 100% offline, privacy-first AI knowledge base on a PC.",
      description: "Install Ollama, download a lightweight open-source LLM, and configure an offline document question-answering tool on a client's computer.",
      category: "BUILD",
      difficulty: "INTERMEDIATE",
      estimatedTime: "4 hours",
      hardwareTier: "TIER_3_POWER",
      whyThisExists: "Professionals like attorneys and accountants cannot send client files to public cloud APIs due to confidentiality laws, but desperately need AI search.",
      whatYouWillBuild: "A private, air-gapped document Q&A assistant running 100% locally on a client's workstation.",
      potentialMonetization: "Charge $400 for local setup and workstation optimization.",
      riskNotes: "Only recommend this mission to users with TIER_3_POWER hardware (16GB+ RAM, decent CPU/GPU).",
      toolSlugs: ["ollama"],
      steps: [
        {
          stepNumber: 1,
          title: "Verify Client Hardware Specifications",
          objective: "Ensure machine has required RAM and storage.",
          instruction: "Check client system settings: Minimum 16GB RAM and 20GB free SSD space. Confirm Windows 11, macOS, or Linux.",
          promptTemplate: null,
          expectedOutput: "Hardware verified as TIER_3_POWER compatible.",
          troubleshooting: "Do not attempt on machines with <8GB RAM; models will crash.",
        },
        {
          stepNumber: 2,
          title: "Install Ollama from Official Website",
          objective: "Download the free open-source local LLM runner.",
          instruction: "Go to ollama.com, download the official installer for the client's OS, and complete setup.",
          promptTemplate: null,
          expectedOutput: "Ollama running in the background system tray.",
          troubleshooting: "Verify installation in terminal by running `ollama --version`.",
        },
        {
          stepNumber: 3,
          title: "Pull a Fast, High-Quality Open Model",
          objective: "Download Llama 3.2 or Mistral 7B.",
          instruction: "Open terminal or command prompt. Run: `ollama run llama3.2` (for fast 3B model) or `ollama run mistral` (for 7B model).",
          promptTemplate: null,
          expectedOutput: "Model weights downloaded and interactive prompt ready.",
          troubleshooting: "First download takes ~5-10 minutes depending on internet speed.",
        },
        {
          stepNumber: 4,
          title: "Test Local Inference Speed",
          objective: "Verify model generates responses in under 2 seconds.",
          instruction: "Type a sample query: 'Summarize the difference between an NDA and a Non-Compete agreement in 3 bullets'. Observe response speed.",
          promptTemplate: null,
          expectedOutput: "Fast, coherent response generated without internet connection.",
          troubleshooting: "Disconnect WiFi to physically demonstrate to client that zero data leaves their machine!",
        },
        {
          stepNumber: 5,
          title: "Install Open-WebUI or AnythingLLM for Desktop",
          objective: "Provide a familiar ChatGPT-like interface for non-technical users.",
          instruction: "Download AnythingLLM (free desktop app from anythingllm.com) and set LLM provider to 'Ollama' (localhost:11434).",
          promptTemplate: null,
          expectedOutput: "Clean, intuitive desktop chat window ready for document uploads.",
          troubleshooting: "AnythingLLM handles PDF indexing locally with zero cloud API keys.",
        },
        {
          stepNumber: 6,
          title: "Create a Dedicated Workspace & Upload Sample PDFs",
          objective: "Index client contracts or manuals into local vector memory.",
          instruction: "Create a workspace named 'Confidential Records'. Drag 3 sample PDF files into the workspace and click 'Embed'.",
          promptTemplate: null,
          expectedOutput: "Documents indexed locally in ChromaDB on their hard drive.",
          troubleshooting: "Keep individual PDFs under 50MB for fastest embedding.",
        },
        {
          stepNumber: 7,
          title: "Test Document Q&A with Strict Sourcing",
          objective: "Demonstrate accurate citations from local files.",
          instruction: "Ask: 'According to page 4 of the contract, what is the termination notice period?'. Verify the local AI quotes exact clauses.",
          promptTemplate: null,
          expectedOutput: "Accurate answer referencing specific document page numbers.",
          troubleshooting: "Set temperature to 0.1 for maximum factual accuracy on legal/financial documents.",
        },
        {
          stepNumber: 8,
          title: "Create a 1-Page Quickstart Cheat Sheet",
          objective: "Leave simple instructions for client staff.",
          instruction: "Print or PDF a simple 3-step guide: (1) Turn on PC, (2) Click AnythingLLM icon, (3) Drop in new PDFs and ask questions.",
          promptTemplate: null,
          expectedOutput: "Professional laminated or PDF cheat sheet for client.",
          troubleshooting: "Non-technical clients appreciate physical laminated cheat sheets.",
        },
        {
          stepNumber: 9,
          title: "Conduct 30-Minute Staff Training Session",
          objective: "Walk the client through searching their real documents.",
          instruction: "Guide the client as they ask questions and upload their first real business document.",
          promptTemplate: null,
          expectedOutput: "Client confident using their private AI.",
          troubleshooting: "Remind them to never upload passwords or sensitive decryption keys.",
        },
        {
          stepNumber: 10,
          title: "Collect Setup Fee and Record in EarnQuest",
          objective: "Submit earnings and log project.",
          instruction: "Collect your $400 setup fee. Submit your invoice proof to EarnQuest to unlock the Entrepreneur tier and claim 300 XP!",
          promptTemplate: null,
          expectedOutput: "Project completed, high XP bonus awarded, verified earnings submitted.",
          troubleshooting: "Offer an optional $50/month quarterly maintenance checkup.",
        },
      ],
    },
  ];

  for (const m of missionsData) {
    const { toolSlugs, steps, ...missionFields } = m;
    const mission = await prisma.mission.create({
      data: {
        ...missionFields,
        versions: {
          create: {
            version: "1.0.0",
            changeLog: "Initial verified release with complete 10-step beginner mode.",
            isCurrent: true,
          },
        },
        tools: {
          create: toolSlugs.map((slug) => ({
            toolId: createdTools[slug].id,
            isRequired: true,
            roleInMission: "Core execution and deliverable creation",
          })),
        },
        steps: {
          create: steps.map((s) => ({
            stepNumber: s.stepNumber,
            title: s.title,
            objective: s.objective,
            instruction: s.instruction,
            promptTemplate: s.promptTemplate,
            expectedOutput: s.expectedOutput,
            troubleshooting: s.troubleshooting,
            isBeginnerEssential: true,
          })),
        },
      },
    });

    // Seed an active user mission for Alex Rivera on mission 1
    if (m.slug === "mission-video-repurposing") {
      const userMission = await prisma.userMission.create({
        data: {
          userId: demoUser.id,
          missionId: mission.id,
          status: "IN_PROGRESS",
          currentStep: 3,
          progress: {
            create: [
              { stepNumber: 1, isCompleted: true, completedAt: new Date(), userNotes: "Account created on CapCut web." },
              { stepNumber: 2, isCompleted: true, completedAt: new Date(), userNotes: "Uploaded sample interview audio." },
              { stepNumber: 3, isCompleted: false, userNotes: "Looking for best 30s hook right now." },
            ],
          },
          projects: {
            create: {
              userId: demoUser.id,
              title: "Podcaster Video Repurposing Pilot",
              description: "Creating 3 sample clips for local fitness podcast.",
              status: "IN_PROGRESS",
              notes: "Goal: send proposal by Friday.",
            },
          },
        },
      });
    }
  }

  // 6. Create Initial Gamification Achievements
  const achievementsData = [
    {
      slug: "hardware-verified",
      title: "Engine Calibrated",
      description: "Completed your browser hardware environment profiling.",
      badgeIcon: "Cpu",
      xpReward: 100,
      requiredTier: "EXPLORER",
    },
    {
      slug: "first-step-completed",
      title: "First Step Forward",
      description: "Successfully executed your first mission step.",
      badgeIcon: "Footprints",
      xpReward: 50,
      requiredTier: "EXPLORER",
    },
    {
      slug: "mission-complete-1",
      title: "Opportunity Architect",
      description: "Completed your first full 10-step mission from discovery to execution.",
      badgeIcon: "CheckCircle",
      xpReward: 250,
      requiredTier: "CREATOR",
    },
    {
      slug: "first-earning-verified",
      title: "Real World Revenue",
      description: "Submitted your first verified external or platform-processed earnings proof.",
      badgeIcon: "DollarSign",
      xpReward: 500,
      requiredTier: "BUILDER",
    },
    {
      slug: "power-tier-unlocked",
      title: "Local AI Champion",
      description: "Configured and ran an offline local AI model on your own hardware.",
      badgeIcon: "Zap",
      xpReward: 350,
      requiredTier: "BUILDER",
    },
  ];

  for (const a of achievementsData) {
    const ach = await prisma.achievement.create({ data: a });
    // Unlock first 2 for demo user
    if (a.slug === "hardware-verified" || a.slug === "first-step-completed") {
      await prisma.userAchievement.create({
        data: {
          userId: demoUser.id,
          achievementId: ach.id,
        },
      });
    }
  }

  // 7. Seed Sample Ledger & Earnings Verification for Demo
  const demoProject = await prisma.project.findFirst({ where: { userId: demoUser.id } });

  // Sample verified external earning of $150.00 (15,000 cents)
  await prisma.earningVerification.create({
    data: {
      userId: demoUser.id,
      projectId: demoProject?.id,
      amountInCents: 15000,
      currency: "USD",
      platformName: "Direct Client (Stripe Invoice)",
      sourceUrl: "https://invoice.stripe.com/demo-invoice-alex",
      status: "VERIFIED",
      reviewerNotes: "Verified receipt showing client payment for short-form video package.",
      submittedAt: new Date(Date.now() - 86400000 * 2),
      reviewedAt: new Date(Date.now() - 86400000),
    },
  });

  // Sample platform ledger entries: customer paid $100.00 (10,000 cents)
  // Gross: 10,000 cents, Platform fee: 2,000 cents, User share: 8,000 cents
  await prisma.ledgerEntry.createMany({
    data: [
      {
        userId: demoUser.id,
        transactionId: "tx_sample_checkout_001",
        type: "CREDIT_SALE_GROSS",
        amountInCents: 10000,
        currency: "USD",
        status: "SETTLED",
        notes: "Platform checkout: Custom Canva Template Pack sale",
      },
      {
        userId: demoUser.id,
        transactionId: "tx_sample_checkout_001",
        type: "DEBIT_PLATFORM_FEE",
        amountInCents: 2000,
        currency: "USD",
        status: "SETTLED",
        notes: "EarnQuest 20% platform fee",
      },
      {
        userId: demoUser.id,
        transactionId: "tx_sample_checkout_001",
        type: "CREDIT_USER_EARNING",
        amountInCents: 8000,
        currency: "USD",
        status: "AVAILABLE",
        notes: "80% creator share allocated to available balance",
      },
    ],
  });

  console.log("✅ EarnQuest database seeded successfully!");
  console.log("   Admin: admin@earnquest.local / AdminPass123!");
  console.log("   Demo User: creator@earnquest.local / CreatorPass123!");
  console.log("   10 Tools, 10 Opportunities, 10 Missions, 5 Achievements initialized.");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
